This reporter outputs "undefined" when run in nodejs.
Found the root cause with the following code:

var oldLog = console.log;
console.log = function(msg) {
  oldLog.apply(console, arguments);
  if (msg === undefined) {
    throw new Error('FOUND IT!');
  }
};

Which provided this output:

Error: FOUND IT!
    at Console.console.log ([project]/test/test_helper.js:16:11)
    at Runner.<anonymous> ([project]/node_modules/mocha/lib/reporters/dot.js:54:13)
    at Runner.EventEmitter.emit (events.js:117:20)
    at [project]/node_modules/mocha/lib/runner.js:596:10
    at [project]/node_modules/mocha/lib/runner.js:517:7
    at next ([project]/node_modules/mocha/lib/runner.js:246:23)
    at Object._onImmediate ([project]/node_modules/mocha/lib/runner.js:275:5)
    at processImmediate [as _immediateCallback] (timers.js:336:15)