Improve Growl message for failed tests
Growl enough information to allow debugging of simply failures based
solely on the information provided by Growl.

Specifically, instead of the traditional notification like

    Title: Failed

    1 of 40 tests failed

display a more detailed notification like

    Title: 1 of 40 tests failed

    Session should monitor the added projects and issue reload requests

    session.js:40

    ReferenceError: foo is not defined