docs: clarify invalid usage of done()
When I first read 
"anything else will cause a failed test"
I considered that this might be a typo,
and that this should say "a passed test"
instead, because after all setting "no error"
could mean "no error", right? I then understood
that this sentence could also mean that
"anything else is a programmer error", i.e. a bug
and I was hoping that in _that_ case a clear
error would be thrown.

I tried things out and indeed found that the latter
is the case

> Error: done() invoked with non-Error: true

This patch attempts to clarify that this is
indeed all about a programmer error.